In [ ]:
print("Accounts Duplicates:", accounts.duplicated().sum())
print("Subscriptions Duplicates:", subscriptions.duplicated().sum())
print("Feature Usage Duplicates:", feature_usage.duplicated().sum())
print("Support Tickets Duplicates:", support.duplicated().sum())
print("Churn Events Duplicates:", churn.duplicated().sum())

In [8]:
subscriptions.describe(include='all')

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
count,5000,5000,5000,486,5000,5000.000000,5000.000000,5000.000000,5000,5000,5000,5000,5000,5000
unique,5000,500,625,208,3,NaN,NaN,NaN,2,2,2,2,2,2
top,S-8cec59,A-d4ac0e,2024-12-31,2024-12-31,Enterprise,NaN,NaN,NaN,False,False,False,False,monthly,True
freq,1,19,45,24,1723,NaN,NaN,NaN,4222,4471,4782,4514,2539,4005
mean,NaN,NaN,NaN,NaN,NaN,29.852000,2267.749400,27212.992800,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,23.089771,3421.375348,41056.504178,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,1.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,14.000000,285.000000,3420.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,24.000000,931.000000,11172.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,40.000000,2786.000000,33432.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,189.000000,33830.000000,405960.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
accounts.describe(include='all')

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
count,500,500,500,500,500,500,500,500.000000,500,500
unique,500,500,5,7,370,5,3,NaN,2,2
top,A-2e4581,Company_0,DevTools,US,2024-10-22,organic,Pro,NaN,False,False
freq,1,1,113,291,4,114,178,NaN,403,390
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.560000,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.044718,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,163.000000,NaN,NaN

In [6]:
print("===== Missing Values =====")

print("\nAccounts")
print(accounts.isnull().sum())

print("\nSubscriptions")
print(subscriptions.isnull().sum())

print("\nFeature Usage")
print(feature_usage.isnull().sum())

print("\nSupport Tickets")
print(support.isnull().sum())

print("\nChurn Events")
print(churn.isnull().sum())

===== Missing Values =====

Accounts
account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

Subscriptions
subscription_id         0
account_id              0
start_date              0
end_date             4514
plan_tier               0
seats                   0
mrr_amount              0
arr_amount              0
is_trial                0
upgrade_flag            0
downgrade_flag          0
churn_flag              0
billing_frequency       0
auto_renew_flag         0
dtype: int64

Feature Usage
usage_id               0
subscription_id        0
usage_date             0
feature_name           0
usage_count            0
usage_duration_secs    0
error_count            0
is_beta_feature        0
dtype: int64

Support Tickets
ticket_id                        0
account_id                       0
submitted_at                     0
closed_at                        0
resolution_time_hours            0
priority                         0
first_response_time_minutes      0
satisfaction_score             825
escalation_flag                  0
dtype: int64

Churn Events
churn_event_id                0
account_id                    0
churn_date                    0
reason_code                   0
refund_amount_usd             0
preceding_upgrade_flag        0
preceding_downgrade_flag      0
is_reactivation               0
feedback_text               148
dtype: int64

In [5]:
print("===== Accounts =====")
print(accounts.dtypes)

print("\n===== Subscriptions =====")
print(subscriptions.dtypes)

print("\n===== Feature Usage =====")
print(feature_usage.dtypes)

print("\n===== Support Tickets =====")
print(support.dtypes)

print("\n===== Churn Events =====")
print(churn.dtypes)

===== Accounts =====
account_id         object
account_name       object
industry           object
country            object
signup_date        object
referral_source    object
plan_tier          object
seats               int64
is_trial             bool
churn_flag           bool
dtype: object

===== Subscriptions =====
subscription_id      object
account_id           object
start_date           object
end_date             object
plan_tier            object
seats                 int64
mrr_amount            int64
arr_amount            int64
is_trial               bool
upgrade_flag           bool
downgrade_flag         bool
churn_flag             bool
billing_frequency    object
auto_renew_flag        bool
dtype: object

===== Feature Usage =====
usage_id               object
subscription_id        object
usage_date             object
feature_name           object
usage_count             int64
usage_duration_secs     int64
error_count             int64
is_beta_feature          bool
dtype: object

===== Support Tickets =====
ticket_id                       object
account_id                      object
submitted_at                    object
closed_at                       object
resolution_time_hours          float64
priority                        object
first_response_time_minutes      int64
satisfaction_score             float64
escalation_flag                   bool
dtype: object

===== Churn Events =====
churn_event_id               object
account_id                   object
churn_date                   object
reason_code                  object
refund_amount_usd           float64
preceding_upgrade_flag         bool
preceding_downgrade_flag       bool
is_reactivation                bool
feedback_text                object
dtype: object

In [4]:
accounts.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [3]:
print("Accounts:", accounts.shape)
print("Subscriptions:", subscriptions.shape)
print("Feature Usage:", feature_usage.shape)
print("Support Tickets:", support.shape)
print("Churn Events:", churn.shape)

Accounts: (500, 10)
Subscriptions: (5000, 14)
Feature Usage: (25000, 8)
Support Tickets: (2000, 9)
Churn Events: (600, 9)

In [2]:
# Load datasets

accounts = pd.read_csv("../data/raw/ravenstack_accounts.csv")
subscriptions = pd.read_csv("../data/raw/ravenstack_subscriptions.csv")
feature_usage = pd.read_csv("../data/raw/ravenstack_feature_usage.csv")
support = pd.read_csv("../data/raw/ravenstack_support_tickets.csv")
churn = pd.read_csv("../data/raw/ravenstack_churn_events.csv")

print("✅ All datasets loaded successfully!")

✅ All datasets loaded successfully!

In [1]:
import pandas as pd
import numpy as np

print("Libraries loaded successfully!")

Libraries loaded successfully!